//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoDream.FileTransfer.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZoDream.FileTransfer.Strings.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Overwrite 的本地化字符串。
        /// </summary>
        internal static string autoOverwrite {
            get {
                return ResourceManager.GetString("autoOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client IP: 的本地化字符串。
        /// </summary>
        internal static string clientIp {
            get {
                return ResourceManager.GetString("clientIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client IP or Port error 的本地化字符串。
        /// </summary>
        internal static string clientIpError {
            get {
                return ResourceManager.GetString("clientIpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client Port 的本地化字符串。
        /// </summary>
        internal static string clientPort {
            get {
                return ResourceManager.GetString("clientPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linked: 的本地化字符串。
        /// </summary>
        internal static string countLabel {
            get {
                return ResourceManager.GetString("countLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ask a link 的本地化字符串。
        /// </summary>
        internal static string linkTo {
            get {
                return ResourceManager.GetString("linkTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Listen 的本地化字符串。
        /// </summary>
        internal static string listen {
            get {
                return ResourceManager.GetString("listen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Listen mode is not open 的本地化字符串。
        /// </summary>
        internal static string listenNotOpen {
            get {
                return ResourceManager.GetString("listenNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success {0} / Failure {1} / Total {2} 的本地化字符串。
        /// </summary>
        internal static string messageTip {
            get {
                return ResourceManager.GetString("messageTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically overwrite or skip files with duplicate names 的本地化字符串。
        /// </summary>
        internal static string overwriteTip {
            get {
                return ResourceManager.GetString("overwriteTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        internal static string path {
            get {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pick 的本地化字符串。
        /// </summary>
        internal static string pick {
            get {
                return ResourceManager.GetString("pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pick Files 的本地化字符串。
        /// </summary>
        internal static string pickFile {
            get {
                return ResourceManager.GetString("pickFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pick Folder 的本地化字符串。
        /// </summary>
        internal static string pickFolder {
            get {
                return ResourceManager.GetString("pickFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please pick folder to save 的本地化字符串。
        /// </summary>
        internal static string pickSaveFolderTip {
            get {
                return ResourceManager.GetString("pickSaveFolderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progress 的本地化字符串。
        /// </summary>
        internal static string progress {
            get {
                return ResourceManager.GetString("progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready Receive 的本地化字符串。
        /// </summary>
        internal static string ReadyReceive {
            get {
                return ResourceManager.GetString("ReadyReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready Send 的本地化字符串。
        /// </summary>
        internal static string ReadySend {
            get {
                return ResourceManager.GetString("ReadySend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Received 的本地化字符串。
        /// </summary>
        internal static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receive Failure 的本地化字符串。
        /// </summary>
        internal static string ReceiveFailure {
            get {
                return ResourceManager.GetString("ReceiveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receive Ignore 的本地化字符串。
        /// </summary>
        internal static string ReceiveIgnore {
            get {
                return ResourceManager.GetString("ReceiveIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receive: 的本地化字符串。
        /// </summary>
        internal static string receiveLabel {
            get {
                return ResourceManager.GetString("receiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receiving 的本地化字符串。
        /// </summary>
        internal static string Receiving {
            get {
                return ResourceManager.GetString("Receiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receiving... 的本地化字符串。
        /// </summary>
        internal static string receivingTip {
            get {
                return ResourceManager.GetString("receivingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remote IP: 的本地化字符串。
        /// </summary>
        internal static string remoteIp {
            get {
                return ResourceManager.GetString("remoteIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remote IP or Port error 的本地化字符串。
        /// </summary>
        internal static string remoteIpError {
            get {
                return ResourceManager.GetString("remoteIpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remote Port: 的本地化字符串。
        /// </summary>
        internal static string remotePort {
            get {
                return ResourceManager.GetString("remotePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save to Folder: 的本地化字符串。
        /// </summary>
        internal static string saveFolder {
            get {
                return ResourceManager.GetString("saveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Failure 的本地化字符串。
        /// </summary>
        internal static string SendFailure {
            get {
                return ResourceManager.GetString("SendFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Ignore 的本地化字符串。
        /// </summary>
        internal static string SendIgnore {
            get {
                return ResourceManager.GetString("SendIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sending 的本地化字符串。
        /// </summary>
        internal static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send: 的本地化字符串。
        /// </summary>
        internal static string sendLabel {
            get {
                return ResourceManager.GetString("sendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sent 的本地化字符串。
        /// </summary>
        internal static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Size 的本地化字符串。
        /// </summary>
        internal static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speed 的本地化字符串。
        /// </summary>
        internal static string speed {
            get {
                return ResourceManager.GetString("speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle 的本地化字符串。
        /// </summary>
        internal static string toggle {
            get {
                return ResourceManager.GetString("toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to passive mode 的本地化字符串。
        /// </summary>
        internal static string toggleTip {
            get {
                return ResourceManager.GetString("toggleTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to active mode 的本地化字符串。
        /// </summary>
        internal static string toggleToTip {
            get {
                return ResourceManager.GetString("toggleToTip", resourceCulture);
            }
        }
    }
}
